## Where the samples will be written
save_data: ../data/run1
## Where the vocab(s) will be written
src_vocab: ../data/run1/vocab.src
tgt_vocab: ../data/run1/vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
  corpus_1:
    path_src: ../data/clean/Europarl/Europarl_train_100k.tok.true.clean.en
    path_tgt: ../data/clean/Europarl/Europarl_train_100k.tok.true.clean.fr
  valid:
    path_src: ../data/clean/Europarl/Europarl_dev_3750.tok.true.clean.en
    path_tgt: ../data/clean/Europarl/Europarl_dev_3750.tok.true.clean.fr

# Where to save the checkpoints
save_model: ../data/model/run1
save_checkpoint_steps: 5000
train_steps: 10000
valid_steps: 8000
report_every: 100

learning_rate: 1.0


# Train on a single GPU
world_size: 1
gpu_ranks: [0]

